### ISSUE TITLE
Can't cross compile in v.0.03

### ISSUE THREAD

**Issue by cniackz** [mattn/go-ieproxy#32] opened 2022-03-08 17:40 UTC
Hello guys,

I work for `MinIO` company. And lately I've been working to understand this issue below coming from `go-ieproxy`:

```sh
# github.com/mattn/go-ieproxy
../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:36:9: undefined: getConf
../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:41:9: undefined: reloadConf
../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:48:2: undefined: overrideEnvWithStaticProxy
../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:53:12: psc.findProxyForURL undefined (type *ProxyScriptConf has no field or method findProxyForURL, but does have FindProxyForURL)
```

I decided to isolate this from our code to understand better, and this is what I did:

1. Created a tmp directory under my home
2. cloned this repository 
3. created these files below and performed cross compilation:

# test.go 
```go
package testing

import (
	"fmt"
	"github.com/mattn/go-ieproxy"
)

func main() {
	ieproxy.GetProxyFunc()
    fmt.Println("hello world")
}
```

# go.mod
```go
module example.com/testing

go 1.17

require github.com/mattn/go-ieproxy v0.0.3

require (
	golang.org/x/net v0.0.0-20220107192237-5cfca573fb4d // indirect
	golang.org/x/sys v0.0.0-20220110181412-a018aaa089fe // indirect
	golang.org/x/text v0.3.7 // indirect
)
```

# go.sum
```go
github.com/mattn/go-ieproxy v0.0.3 h1:YkaHmK1CzE5C4O7A3hv3TCbfNDPSCf0RKZFX+VhBeYk=
github.com/mattn/go-ieproxy v0.0.3/go.mod h1:6ZpRmhBaYuBX1U2za+9rC9iCGLsSp2tftelZne7CPko=
golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2/go.mod h1:djNgcEr1/C05ACkg1iLfiJU5Ep61QUkGW8qpdssI0+w=
golang.org/x/net v0.0.0-20220107192237-5cfca573fb4d h1:62NvYBuaanGXR2ZOfwDFkhhl6X1DUgf8qg3GuQvxZsE=
golang.org/x/net v0.0.0-20220107192237-5cfca573fb4d/go.mod h1:9nx3DQGgdP8bBQD5qxJ1jj9UTztislL4KSBs9R2vV5Y=
golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a/go.mod h1:STP8DvDyc/dI5b8T5hshtkjS+E42TnysNCUPdjciGhY=
golang.org/x/sys v0.0.0-20201119102817-f84b799fce68/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
golang.org/x/sys v0.0.0-20210423082822-04245dca01da/go.mod h1:h1NjWce9XRLGQEsW7wpKNCjG9DtNlClVuFLEZdDNbEs=
golang.org/x/sys v0.0.0-20220110181412-a018aaa089fe h1:W8vbETX/n8S6EmY0Pu4Ix7VvpsJUESTwl0oCK8MJOgk=
golang.org/x/sys v0.0.0-20220110181412-a018aaa089fe/go.mod h1:oPkhp1MJrh7nUepCBck5+mAzfO9JrbApNNgaTdGDITg=
golang.org/x/term v0.0.0-20201126162022-7de9c90e9dd1/go.mod h1:bj7SfCRtBDWHUb9snDiAeCFNEtKQo2Wmx5Cou7ajbmo=
golang.org/x/text v0.3.6/go.mod h1:5Zoc/QRtKVWzQhOtBMvqHzDpF6irO9z98xDceosuGiQ=
golang.org/x/text v0.3.7 h1:olpwvP2KacW1ZWvsR7uQhoyTYvKAupfQrRGBFM352Gk=
golang.org/x/text v0.3.7/go.mod h1:u+2+/6zg+i71rQMx5EYifcz6MCKuco9NR6JIITiCfzQ=
golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
cniackz:/Users/cniackz/tmp # 
```

# Cross compilation
```sh
cniackz:/Users/cniackz/tmp # CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 GO111MODULE=on go build
cniackz:/Users/cniackz/tmp # CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GO111MODULE=on go build
# github.com/mattn/go-ieproxy
../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:36:9: undefined: getConf
../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:41:9: undefined: reloadConf
../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:48:2: undefined: overrideEnvWithStaticProxy
../go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.3/ieproxy.go:53:12: psc.findProxyForURL undefined (type *ProxyScriptConf has no field or method findProxyForURL, but does have FindProxyForURL)
```

Notice how above is failing the same way, the question I have is:
Why `getConf` is undefined?, If I can see it is defined for `darwin` under `ieproxy_darwin.go`

```go
// GetConf retrieves the proxy configuration from the Windows Regedit
func getConf() ProxyConf {
	once.Do(writeConf)
	return darwinProxyConf
}
```

Can you help me to understand better what could be?.

Thank you in advance for your help.

**Comment by harshavardhana** [comment] 2022-03-08 17:47
Duplicate of https://github.com/mattn/go-ieproxy/issues/30

**Closed** 2022-03-13 12:13 UTC
